import type { Localized } from "@/lib/i18n";

/**
 * Localized label for every distinct `categoryRaw` value found in
 * src/data/places.ts (the spreadsheet's own free-text Category column,
 * 24 distinct values). Used by PlaceCard so the category shown in the
 * UI is translated instead of always displaying the raw English text.
 */
export const categoryRawLabels: Record<string, Localized> = {
  Activity: {
    en: "Activity",
    ja: "アクティビティ",
    vi: "Hoạt động",
    zh: "活动体验",
    ko: "액티비티",
    de: "Aktivität",
    ru: "Активность",
  },
  Attraction: {
    en: "Attraction",
    ja: "見どころ",
    vi: "Điểm tham quan",
    zh: "景点",
    ko: "명소",
    de: "Sehenswürdigkeit",
    ru: "Достопримечательность",
  },
  Bakery: {
    en: "Bakery",
    ja: "ベーカリー",
    vi: "Tiệm bánh",
    zh: "面包店",
    ko: "베이커리",
    de: "Bäckerei",
    ru: "Пекарня",
  },
  "Bakery / Café": {
    en: "Bakery & Café",
    ja: "ベーカリー・カフェ",
    vi: "Tiệm bánh & Cà phê",
    zh: "面包店与咖啡馆",
    ko: "베이커리·카페",
    de: "Bäckerei & Café",
    ru: "Пекарня и кафе",
  },
  Café: {
    en: "Café",
    ja: "カフェ",
    vi: "Quán cà phê",
    zh: "咖啡馆",
    ko: "카페",
    de: "Café",
    ru: "Кафе",
  },
  "Café & Bakery": {
    en: "Café & Bakery",
    ja: "カフェ・ベーカリー",
    vi: "Cà phê & Tiệm bánh",
    zh: "咖啡馆与面包店",
    ko: "카페·베이커리",
    de: "Café & Bäckerei",
    ru: "Кафе и пекарня",
  },
  "Café / Sushi": {
    en: "Café & Sushi",
    ja: "カフェ・寿司",
    vi: "Cà phê & Sushi",
    zh: "咖啡馆／寿司",
    ko: "카페·스시",
    de: "Café & Sushi",
    ru: "Кафе и суши",
  },
  Culture: {
    en: "Culture",
    ja: "文化",
    vi: "Văn hoá",
    zh: "文化",
    ko: "문화",
    de: "Kultur",
    ru: "Культура",
  },
  "Culture / Attraction": {
    en: "Culture & Attraction",
    ja: "文化・見どころ",
    vi: "Văn hoá & Tham quan",
    zh: "文化与景点",
    ko: "문화·명소",
    de: "Kultur & Sehenswürdigkeit",
    ru: "Культура и достопримечательность",
  },
  "Italian / Restaurant": {
    en: "Italian Restaurant",
    ja: "イタリアン・レストラン",
    vi: "Nhà hàng Ý",
    zh: "意式餐厅",
    ko: "이탈리안 레스토랑",
    de: "Italienisches Restaurant",
    ru: "Итальянский ресторан",
  },
  "Local Food": {
    en: "Local Food",
    ja: "地元グルメ",
    vi: "Ẩm thực địa phương",
    zh: "当地美食",
    ko: "로컬 푸드",
    de: "Lokale Küche",
    ru: "Местная еда",
  },
  Nature: {
    en: "Nature",
    ja: "自然",
    vi: "Thiên nhiên",
    zh: "自然",
    ko: "자연",
    de: "Natur",
    ru: "Природа",
  },
  "Nature / Scenic": {
    en: "Nature & Scenery",
    ja: "自然・景勝地",
    vi: "Thiên nhiên & Cảnh đẹp",
    zh: "自然与景观",
    ko: "자연·경관",
    de: "Natur & Landschaft",
    ru: "Природа и пейзажи",
  },
  Omiyage: {
    en: "Omiyage",
    ja: "お土産",
    vi: "Quà lưu niệm",
    zh: "伴手礼",
    ko: "기념품",
    de: "Souvenirs",
    ru: "Сувениры",
  },
  "Omiyage / Shopping": {
    en: "Omiyage & Shopping",
    ja: "お土産・買い物",
    vi: "Quà lưu niệm & Mua sắm",
    zh: "伴手礼与购物",
    ko: "기념품·쇼핑",
    de: "Souvenirs & Einkaufen",
    ru: "Сувениры и покупки",
  },
  Onsen: {
    en: "Onsen",
    ja: "温泉",
    vi: "Suối nước nóng",
    zh: "温泉",
    ko: "온천",
    de: "Onsen",
    ru: "Онсэн",
  },
  Outdoor: {
    en: "Outdoor",
    ja: "アウトドア",
    vi: "Ngoài trời",
    zh: "户外",
    ko: "아웃도어",
    de: "Outdoor",
    ru: "На природе",
  },
  Restaurant: {
    en: "Restaurant",
    ja: "レストラン",
    vi: "Nhà hàng",
    zh: "餐厅",
    ko: "레스토랑",
    de: "Restaurant",
    ru: "Ресторан",
  },
  "Restaurant / Diner": {
    en: "Restaurant & Diner",
    ja: "レストラン・ダイナー",
    vi: "Nhà hàng kiểu Mỹ (Diner)",
    zh: "餐厅／美式餐馆",
    ko: "레스토랑·다이너",
    de: "Restaurant & Diner",
    ru: "Ресторан и дайнер",
  },
  Shopping: {
    en: "Shopping",
    ja: "ショッピング",
    vi: "Mua sắm",
    zh: "购物",
    ko: "쇼핑",
    de: "Einkaufen",
    ru: "Покупки",
  },
  Soba: {
    en: "Soba",
    ja: "そば",
    vi: "Mì Soba",
    zh: "荞麦面",
    ko: "소바",
    de: "Soba",
    ru: "Соба",
  },
  "Soba / Udon": {
    en: "Soba & Udon",
    ja: "そば・うどん",
    vi: "Mì Soba & Udon",
    zh: "荞麦面与乌冬面",
    ko: "소바·우동",
    de: "Soba & Udon",
    ru: "Соба и удон",
  },
  Sweets: {
    en: "Sweets",
    ja: "スイーツ",
    vi: "Đồ ngọt",
    zh: "甜点",
    ko: "디저트",
    de: "Süßes",
    ru: "Сладости",
  },
  "Tourist Information": {
    en: "Tourist Information",
    ja: "観光案内",
    vi: "Thông tin du lịch",
    zh: "旅游信息",
    ko: "관광 안내",
    de: "Touristeninformation",
    ru: "Туристическая информация",
  },
};

/** Localized label for a place's raw category; falls back to the raw text itself. */
export function categoryLabel(categoryRaw: string): Localized {
  return categoryRawLabels[categoryRaw] ?? { en: categoryRaw };
}
